name: ShopDemo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  keyboard_actions: ^3.4.4
  build_runner: ^2.1.4
  get: ^4.3.8
  provider: ^6.0.1
  get_it: ^7.2.0
  flutter_local_notifications: ^9.0.2
  flutter_datetime_picker:     
    git:
        url: https://github.com/Realank/flutter_datetime_picker.git
        ref: master 
  intl: ^0.17.0
  timer_builder: ^2.0.0
  visibility_detector: ^0.2.2

  #UI
  font_awesome_flutter: ^9.2.0
  carousel_slider: ^4.0.0
  animate_do: ^2.0.0
  scroll_to_index: ^2.1.0
  sticky_headers: ^0.2.0
  loading_animations: ^2.2.0
  scrollable_positioned_list: ^0.2.2
  flutter_native_splash: ^1.3.1
  flutter_launcher_icons: ^0.9.2
  #Firebase
  firebase_auth: ^3.1.4
  firebase_messaging: ^10.0.9
  # firebase_chat: ^0.0.3

  google_sign_in: ^5.2.1
  cloud_firestore: ^2.5.4
  shared_preferences: ^2.0.8
  image_picker: ^0.8.4+4
  google_fonts: ^2.1.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
flutter_native_splash:
  image: "assets/images/app_logo.png"
  color: "#FFFFFF"
  android: true
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - 'assets/images/'
    - 'assets/fonts/'
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Black.ttf
        - asset: assets/fonts/SourceSansPro-BlackItalic.ttf
        - asset: assets/fonts/SourceSansPro-Light.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-Light.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"